TASK = "MNIST"
NET_PATH = "./SNN-forwardforward/logs/analyze/MNIST_91.pth"

POST_NEURONS = 256
POST_PARALLEL = 8
POST_DATA_WIDTH = 20
POST_SRAM_DATA_WIDTH = int(POST_PARALLEL * POST_DATA_WIDTH)
POST_SRAM_DEPTH = int(POST_NEURONS / POST_PARALLEL)

PRE_NEURONS = 784
PRE_PARALLEL = 1
PRE_DATA_WIDTH = 7
PRE_SRAM_DATA_WIDTH = int(PRE_PARALLEL * PRE_DATA_WIDTH)
PRE_SRAM_DEPTH = int(PRE_NEURONS / PRE_PARALLEL)

WEIGHT_MAX = 1
WEIGHT_WIDTH = 9
WEIGHT_SCALE = WEIGHT_MAX / (2 ** (WEIGHT_WIDTH - 1))

INPUT_MAX = 2 ** 3
INPUT_WIDTH = 8 
INPUT_SCALE = INPUT_MAX / (2 ** (INPUT_WIDTH - 1))

BIAS_MAX = 2 ** 7
BIAS_WIDTH = 16
BIAS_SCALE = BIAS_MAX / (2 ** (BIAS_WIDTH - 1))

OUTPUT_WIDTH = 16
OUTPUT_SCALE = WEIGHT_SCALE * INPUT_SCALE
OUTPUT_MAX = OUTPUT_SCALE * (2 ** (OUTPUT_WIDTH - 1))

T = 8
V_THRESHOLD_POS = 1.2
V_THRESHOLD_NEG = -1.2
THETA = 0.25